import base64
import secrets
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import paramiko

ROOT = Path(__file__).resolve().parents[1]


def run_command(args, **kwargs):
    return subprocess.run(
        args,
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=True,
        timeout=30,
        **kwargs,
    ).stdout


def main():
    # Read the lab server's public host key through Docker.
    public_key = run_command([
        "docker", "compose", "exec", "-T", "ssh-server",
        "cat", "/etc/ssh/ssh_host_ed25519_key.pub",
    ])
    host_key = paramiko.Ed25519Key(
        data=base64.b64decode(public_key.split()[1])
    )

    started = datetime.now(timezone.utc).isoformat()

    # A unique nonexistent account identifies this demo's events.
    username = "demo_" + secrets.token_hex(6)

    for attempt in range(1, 4):
        client = paramiko.SSHClient()
        client.get_host_keys().add(
            "[127.0.0.1]:2222", "ssh-ed25519", host_key
        )
        try:
            client.connect(
                hostname="127.0.0.1",
                port=2222,
                username=username,
                password=secrets.token_urlsafe(24),
                allow_agent=False,
                look_for_keys=False,
                timeout=5,
                banner_timeout=5,
                auth_timeout=10,
            )
        except paramiko.AuthenticationException:
            print(f"[DEMO] Expected login failure {attempt}/3")
        else:
            raise RuntimeError("Unexpected successful login")
        finally:
            client.close()

    logs = run_command([
        "docker", "compose", "logs",
        "--no-color", "--no-log-prefix", "--timestamps",
        "--since", started, "ssh-server",
    ])

    # Select only the failed logins generated by this run.
    marker = f"Failed password for invalid user {username} "
    demo_logs = "\n".join(
        line for line in logs.splitlines() if marker in line
    )

    result = run_command(
        [sys.executable, str(ROOT / "scripts" / "detect_ssh.py")],
        input=demo_logs,
    )
    print(result, end="")

    if "[SUMMARY] failed_logins=3 alerts=1" not in result:
        raise RuntimeError(
            "Expected 3 failed logins and 1 alert; inspect server logs"
        )

    print("[PASS] Attack simulation -> logs -> detection")


if __name__ == "__main__":
    try:
        main()
    except (OSError, subprocess.SubprocessError,
            paramiko.SSHException, RuntimeError, ValueError) as error:
        print(f"[ERROR] {error}", file=sys.stderr)
        sys.exit(1)